### ISSUE TITLE
Update to match current brainblocks

### ISSUE THREAD

**Issue by schenkty** [brainblocks/LdRaiblocksIntegration#1]
Hey can you check and see if anything needs updated so it can match the current state of brainblocks.

Thanks,
Ty

**Comment by LucaDe** [comment]
Hey, yes ofc. I’ll check it on the weekend ;)

**Comment by schenkty** [comment]
Hey @LucaDe any updates on this?

**Comment by LucaDe** [comment]
Hey @schenkty,
sorry for the delay. Been quite busy in the last days. I just ensured, that everything still works as expected and renamed everything from Raiblocks to Nano. It would be great, if you could change the Repo's name to LdNanoIntegration for the sake of completeness :)

**Comment by schenkty** [comment]
Looks Great! Thank you for updating the plugin. I have updated the repo as well
